import Head from "next/head";
import Image from "next/image";
import Fade from "react-reveal/Fade";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Astrology and Horoscope</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="header flex flex-row justify-evenly mt-5 ">
          <div className="logo cursor-pointer">
            <img src="/astrology_api_color.png" />
          </div>
          <div>
            <ul className="flex flex-row space-x-20 mt-1 text-slate-500 font-medium text-lg hover:text-blue  cursor-pointer">
              <li>Home</li>
              <li>Features</li>
              <li>Pricing</li>
              <li>Demo</li>
              <li>Documentation</li>
              <li>Login</li>
            </ul>
          </div>
          <div className="mr-20  cursor-pointer">
            <button className="text-lg px-5 py-1 rounded-md bg-blue-600 text-white hover:-translate-y-0.5 hover:transition hover:ease-in-out hover:delay-150 hover:shadow-xl">
              Try Free
            </button>
          </div>
        </div>
        <div className="section-1 flex flex-row justify-center mt-28">
          <Fade bottom>
            <div className="left float-left max-w-lg">
              <p className="text-5xl text-left  text-slate-800">
                Bring <span className="text-blue-500">Astrology</span> to your
                apps and websites.
              </p>
              <p className="text-2xl mt-5 text-slate-400">
                Want to push up audience engagement on your website & app? Pin
                up sticky astrology content with our API
              </p>
              <div className="">
                <input
                  type="text"
                  placeholder="Enter your email"
                  class="my-5 py-4 pr-16 pl-3  text-lg border border-gray-400 rounded focus:outline-none "
                ></input>
                <button className="text-lg py-4 pr-16 pl-3 ml-4 rounded-md bg-blue-600 text-white hover:-translate-y-0.5 hover:transition hover:ease-in-out hover:delay-150 hover:shadow-xl">
                  Get Started
                </button>
              </div>
            </div>
          </Fade>
          <Fade bottom>
            <div className="right float-right w-2/5 h-2/5">
              <img src="/illustration-10.png"></img>
            </div>
          </Fade>
        </div>
        <div className="flex  flex-col items-center mt-9 z-10 bg-white">
          <p className="text-4xl ">
            Fully Customizable{" "}
            <span className="text-blue-500">Astrology Solution</span>
          </p>
          <p className="mt-2 text-2xl text-slate-400">
            Subscribe-Integrate-Run with out{" "}
            <span className="text-slate-700">Astrology as a Service</span>{" "}
            Platform
          </p>
        </div>
      </main>
    </div>
  );
}
